import moment from "moment"
export const createDateFromStr = str =>
  moment(str, [
    "MM-DD-YYYY",
    "DD-MM-YYYY",
    "DD-MM",
    "MM-DD-YY",
    "DD-MM-YY",
    "MMM, Do  YYYY",
    "MMM Do YYYY",
    "MMM Do YYYY",
    "MMM, Do YY",
    "MMM Do YY",
    "MMM Do YY",
    "MMMM, Do, YYYY",
    "MMMM Do, YYYY",
    "MMMM Do, YYYY",
    "MMMM, Do, YY",
    "MMMM Do, YY",
    "MMMM Do, YY",
    "Do, MMM, YYYY",
    "Do, MMM YYYY",
    "Do MMM YYYY",
    "Do, MMM, YY",
    "Do, MMM YY",
    "Do MMM YY",
    "Do, MMMM, YYYY",
    "Do, MMMM YYYY",
    "Do MMMM YYYY",
    "Do, MMMM, YY",
    "Do, MMMM YY",
    "Do MMMM YY",
  ])
