import moment from "moment"
export const createDateFromStr = str =>
  moment(str, [
    "MM-DD-YYYY",
    "DD-MM-YYYY",
    "MM-DD-YY",
    "DD-MM-YY",
    "MMM, Do  YYYY",
    "MMM Do YYYY",
    "MMM Do YYYY",
    "MMM, Do YY",
    "MMM Do YY",
    "MMM Do YY",
    "MMMM, Do, YYYY",
    "MMMM Do, YYYY",
    "MMMM Do, YYYY",
    "MMMM, Do, YY",
    "MMMM Do, YY",
    "MMMM Do, YY",
    "MMM Do",
    "Do MMM",
    "Do, MMM, YYYY",
    "Do, MMM YYYY",
    "Do MMM YYYY",
    "Do, MMM, YY",
    "Do, MMM YY",
    "Do MMM YY",
    "Do, MMMM, YYYY",
    "Do, MMMM YYYY",
    "Do MMMM YYYY",
    "Do, MMMM, YY",
    "Do, MMMM YY",
    "Do MMMM YY",
  ])

export const createTimeFromStr = str =>
  moment(str, [
    "H:m",
    "H:mm",
    "HH:mm",
    "h:ma",
    "h:m a",
    "h:mma",
    "h:mm a",
    "hh:mma",
    "hh:mm a",
  ])
